### ISSUE TITLE
Bindings for custom "insert modes" where regular insert-state doesn't make sense

### ISSUE THREAD

**Issue by terlar** [emacs-evil/evil-collection#106]
Some modes where insert-state doesn't make sense, but have some kind of mode that can be triggered to do edits.

# Examples

### ivy-occur-grep-mode
- `i` would run `ivy-wgrep-change-to-wgrep-mode`
### wgrep-mode
- `ZQ` would run `wgrep-abort-changes`
- `ZZ` would run `wgrep-finish-edit`

### dired-mode
- `i` would run `dired-toggle-read-only` (which triggers `wdired-mode`)
- `I` would run `dired-maybe-insert-subdir` (since this is currently bound to `i`)
### wdired-mode
- `ZQ` would run `wdired-abort-changes`
- `ZZ` would run `wdired-finish-edit`

I am not sure if the binding should be `i` or something else, what do you think? Does this sound like a good idea? There is probably more states where regular insert state wouldn't make sense but we have some kind of mode that would change into an editable state.

**Comment by Ambrevar** [comment]
Right now we have `C-x C-q`, which is definitely very emacs-y, and your suggestion makes sense in my opinion.  At first glance, I'd agree with adding this to the rationale.
@jojojames ?

**Comment by jojojames** [comment]
One thing I like about C-x C-q is that you can do it for both entering and existing that state.

If we go with i, we'll need a second binding to leave it (ZQ/ZZ as mentioned above are some ways to exit). 

Maybe we should add ESC in Normal state to fully exit wdired?

Normal State:
i -> enter wdired-like mode
ESC -> exit wdired-like mode
ZZ -> Abort Changes
ZZ -> Finish wdired

**Comment by Ambrevar** [comment]
`C-x C-q` would still work anyways, we don't have to unbind it.  We can make everyone happy! :)

**Comment by dieggsy** [comment]
I think for wdired mode it would make sense to do something like what @noctuid suggests in https://github.com/emacs-evil/evil-collection/issues/107.

**Comment by noctuid** [comment]
Agreed, same for wgrep.

**Comment by jojojames** [comment]
One thing that makes me hesitant about that (:q/:wq) is that wdired/w-ag/w-ivy is that their presentation is more similar to another 'state' and not a new mode/window.

Org-capture for instance opens up a new window so typing :q/:wq has a DWIM feel to it (in that the window goes away). If I type :q/:wq in a dired window that happens to have wdired turned on, personally I'd think it'd exit the entire window (similar to quit-window) instead of exiting wdired. So I think the usage there might be a little ambiguous. 

This rationale can also extend to other similar (special editing states) like maybe iedit. I think pressing esc while in normal state while in iedit-mode exiting iedit-mode seems to be a good experience. (Caveat: I don't think we have an integration for iedit yet but that's a good example.)

Open to going with a consensus, of course. @Somelauw

**Comment by noctuid** [comment]
I think `:w` at least would make sense for these modes.

**Comment by jojojames** [comment]
Made the changes for this. If there's any other tweaks to the rationale, we can open a new issue or PR.
