### ISSUE TITLE
evil-collection in terminal

### ISSUE THREAD

**Issue by jojojames** [emacs-evil/evil-collection#217]
Anyone use emacs in the terminal/CLI instead of GUI and ran into any pitfalls with evil-collection?

I am planning on making sure evil-collection works OK with CLI interface in emacs. Any suggestions or known issues, feel free to raise.

**Comment by jojojames** [comment]
I've been using emacs in the terminal for a few weeks now and it seems to work fairly well so I'll close this and make necessary tweaks as I see them.

**Comment by yunhao94** [comment]
I've found an issue that, the keycode of the <kbd>Enter</kbd> key is <kbd>RET</kbd> in terminal/CLI, but <kbd>\<return></kbd> in GUI, which leads to different behaviors sometimes.

For example, in [evil-collection-occur.el](https://github.com/emacs-evil/evil-collection/blob/master/evil-collection-occur.el),  `occur-mode-goto-occurrence` is only bind to <kbd>\<return></kbd>, and the function binded to <kbd>RET</kbd> is still `evil-ret` in terminal/CLI, which means users may not get the goodness of evil-collection in terminal/CLI.

I'm not familiar with emacs' keybinding system, is it better to bind <kbd>RET</kbd> once more, or change all the <kbd>\<return></kbd>  to <kbd>RET</kbd> because I've seen `RET (translated from <return>)` when I describe-key in vanilla GUI emacs.

**Comment by jojojames** [comment]
@Ambrevar @noctuid What do you guys think?

**Comment by Ambrevar** [comment]
Yes, `RET` is the way to go.  That's what upstream Emacs uses.

**Comment by jojojames** [comment]
@Ambrevar You mean it's safe to replace all occurencs of <return> with RET, right? If so, that sounds good with me.

**Comment by Ambrevar** [comment]
I think it is.

**Comment by noctuid** [comment]
`<return>` is preferable in GUI Emacs if you want to be able to bind `C-m` to something different, but it's probably fine to just bind `RET` instead for simplicity. It wouldn't be very hard for a user to change.

**Comment by jojojames** [comment]
Sounds good, @yunhao94 , thanks for the report. Hope it works out fine for ya now.

I might've missed a few spots or there may be duplicate RET keybinds.
