### ISSUE TITLE
Define a consistent binding for next-error and previous-error

### ISSUE THREAD

**Issue by hammerandtongs** [emacs-evil/evil-collection#224]
The next-error and previous-error commands work reasonably well (and are very handy) with flycheck working.

What should be the consistent keybind policy from evil-collection?

**Comment by jojojames** [comment]
I've been using 

```
  (define-key flymake-mode-map (kbd "M-n") 'flymake-goto-next-error)
  (define-key flymake-mode-map (kbd "M-p") 'flymake-goto-prev-error)
```
for flymake. Would be open to something consistent across packages or just leave it to the user too.

**Comment by hammerandtongs** [comment]
So it turns out 

`:cfirst
:cnext
:cprevious`

All work right with Evil and this is the Vim method these days I think.

I was hoping to find something consistent in the Vim world that evil-collection could use and this seems to be it?

**Comment by jojojames** [comment]
Do you have further suggestions @hammerandtongs ?

**Comment by hammerandtongs** [comment]
:cnext has been more comfortable for me then M-x next-error so I won't move into a keybinding.

This does call back to #64 

evil-unimpaired seems like a sensible way forward, is this viable these days? 

It's seems pretty limited compared to Tim Pope's version but has a lot of potential.

As I look at the issue it seems like adopting evil-unimpaired into evil-collection more generally might solve this issue and have some nice mappings all around... unimpaired is adopted by the Pope of Vim afterall ;)

**Comment by jojojames** [comment]
Added something unimpaired-like for this. I added two basic functionalities to it (next-buffer and next-error). I'm not married to next-error's binding so feel free to PR if you think a better one exists.

I'd like people to improve that file (adding more appropriate bindings/functions) with PRs though since I'm not too versed in the usecases of unimpaired specific keys unimpaired uses. @bling @hammerandtongs @ajgrf please improve it if you see fit!
