### ISSUE TITLE
Dired mappings should try to be netrw compatible

### ISSUE THREAD

**Issue by Wagk** [emacs-evil/evil-collection#227]

**Comment by jojojames** [comment]
Can you add more details?

**Comment by Wagk** [comment]
Here's a [list of mappings for netrw](https://gist.github.com/danidiaz/37a69305e2ed3319bfff9631175c5d0f#file-netrw-txt)

I don't think we can or should cover everything, but interesting commands include the `m*` series, which affect marking, `-` going up a directory, `t` for entering a file in the new tab, etc.

**Comment by jojojames** [comment]
I think '-' is definitely doable to add and we should think about adding that to other modes to 'go up' too.

The m* series of marking might be trickier considering since the rationale for marking should be consistent across most modes. 'mf' and 'mF' to mark/unmark seem to be pretty heavy (I often hold the m key down to mark multiple files in succession). I'm not sure how heavy the mark/sweep pattern is for netrw but Emacs uses it a lot. 't' also seems to be tricky given it's a very nice key for toggling a mark.

I'm definitely open to changing keybinds if they make sense though.

I think there are binds like p/P to preview/browse in previously used windows is interesting and might be interesting to use in the rationale for other modes too. Seems like a good key for [p]review.

As for other binds, it might make more sense to think about what you'd want changed from dired to netrw and propose suggestions that way!

I didn't use netrw much so I don't know what some of those commands even do.

**Comment by jojojames** [comment]
@Ambrevar What do you think about "-" instead of "^" for "up directory/ up *"? It would save one key press (shift) and also return ^ to the user in most cases. It also doesn't seem to be that useful, (goto previous line in most cases).

I added a bind for dired but wondering about the others.

**Comment by Ambrevar** [comment]
In notmuch and elfeed, "-" is used to remove tags.
Other than that, no strong opinion ;)

**Comment by jojojames** [comment]
Should we move that to "_"? It'd have a parallel with "+" right? Then we can use - for up/up *

**Comment by Ambrevar** [comment]
Hmmm, not sure, at first glance I'd rather not.  It's OK in my opinion
to have "-" serving different purposes.

**Comment by jojojames** [comment]
@Ambrevar I agree about keys serving different purposes. Though I would've expected notmuch (and maybe elfeed) to have a use for the 'up directory/up thread' command (aka collision). So then '-' might be more appropriate as up directory/up thread and '_' might be better as remove tag. (Given +/_ are closer parallels movement-wise than +/- and 'up-thread/up-directory' might be a more common use-case than 'remove tag'.

Up to you though, we can revisit in the future. I don't use elfeed and don't use notmuch enough to have a preference on those binds.

--

I'll close this for now too, not sure there's more to discuss here. If @Wagk have specific keys in mind that would make dired better, we can reopen and discuss them individually.
