### ISSUE TITLE
Dired : integrate Ex[plore] ?

### ISSUE THREAD

**Issue by pyluyten** [emacs-evil/evil-collection#233]
I proposed to evil to add an alias so `:Ex` would work in Emacs. But "evil's goal is not to implement the entirety of Vim commands in Emacs".

so i think evil-collection, despite it is first about bindings, might be the right place to include the snippet i was suggested

    `(evil-ex-define-cmd "Ex[plore]" 'dired-jump)`

**Comment by jojojames** [comment]
Like https://github.com/emacs-evil/evil-collection/issues/107 , I think the :ex type commands would fall under bindings too so I'd definitely support them.

I think global level bindings (like the one you're suggesting) would have to go in evil-collection.el somewhere though. (Since dired may be autoloaded).

I haven't done much research on the ex-cmds but how easy is it for a user to override the ones we set from evil-collection? Anyone else know @noctuid @Ambrevar ?

If it's easy, we should just have a list of global ex commands and just define them at the start.

The ones in the ^linked thread above are mode specific binds (that we haven't really gotten around to binding though).

**Comment by Ambrevar** [comment]
I don't use ex commands much at all (beside :s mostly).
But I'm curious as to why others would use it and I'd like to see if I
could benefit more from using them.
If anyone is willing to do a sales pitch! :)

**Comment by jojojames** [comment]
I don't use it much either but that's more because I don't know many of them aside from the common ones like :w and :e.

**Comment by jojojames** [comment]
@pyluyten I read your other thread. I'm not sure why you think it's a no-go? Anyways, since @edkolev supports it too, I'll close this thread.

For the record, in case anyone stumbles on this. Open to a PR supporting something like this but since @Ambrevar and I don't use these types of commands much, we probably won't do it ourselves.
