### ISSUE TITLE
Cannot insert the selected item in completion menu in Company mode

### ISSUE THREAD

**Issue by linwaytin** [emacs-evil/evil-collection#239]
Before enabling evil-collection, I can hit the Enter key to insert the selected item provided by company mode. 

After enabling evil-collection, hitting Enter generates a new line, and nothing is inserted. The popup completion list is still there, but I cannot find out a key to insert the selected word.

Setting `evil-collection-company-use-tng` to `nil` seems to solve the problem, so it seems the default value `t` causes the problem.

I guess this is related to #72.

**Comment by jojojames** [comment]
Yes, see here: https://github.com/emacs-evil/evil-collection#configuration

**Comment by linwaytin** [comment]
Thanks. I would suggest change the default to nil. It's weird that the default setting cannot work.

**Comment by twlz0ne** [comment]
Setting `evil-collection-company-use-tng` to `nil` not work for me.  Should I restart Emacs?

**Comment by jojojames** [comment]
> Should I restart Emacs?

Yes.

**Comment by yyoncho** [comment]
> Thanks. I would suggest change the default to nil. It's weird that the default setting cannot work.

I second that  - company-tng is not a good fit for all backends and it is especially troublesome with lsp-mode due to protocol specifics. We have received dozens of bug reports/questions and overall it is very confusing for the users(even the one coming from vim).

**Comment by dgutov** [comment]
@yyoncho Same here, it's confusing for the users to have this by default.

Though I wonder how [YouCompleteMe](https://github.com/ycm-core/YouCompleteMe#intro) provides the UI it has while still being able to use LSP as completion source.

**Comment by dgutov** [comment]
Do Vim users expect RET (or some other key) to insert the current completion, though?

As a separate development, we could also make `company-tng` a bit more friendly (if it isn't yet).

**Comment by jojojames** [comment]
If company-tng is not a good fit for those backends, I think improving that flow, as @dgutov mentioned, is a good idea. (irrespective of the default here) I don't use lsp-mode so was not aware of the experience of lsp-mode+company, so I'm happy you've brought it to my attention.

> Do Vim users expect RET (or some other key) to insert the current completion, though?

I haven't kept up to date in vim land for a while. I'd not be surprised if there's a new package they use for completion.

> We have received dozens of bug reports/questions and overall it is very confusing for the users(even the one coming from vim).

Can you link some of them so I can get a better picture? (My 2c, is you'll still get bug reports from the cohort of people using lsp-mode + company, so it's more fruitful to fix whatever interactions are between the two.)


Digressing, this particular bug report we're discussing on, seems to be due to the user not reading the readme. For that type of reasoning (not reading documentation, etc), I'm not interested in changing the default.

If it's more due to the interactions between lsp-mode + company + company-tng + evil-collection, that might be a better discussion to have with solutions other than changing the default. 

As for changing the default, I'm a little torn on the issue. evil-collection does -a lot-, keybindings, integrations, etc. It's not surprising users will get confused by a default here and there (this happens with other modes other than company too). The philosophy here has always been more along the lines of 'enable everything, let the user disable what they don't want' whereas it seems most emacs packages are the reverse 'enable nothing, let the user enable what they want'. If we were to do the latter, I don't think this package would have been as useful.

In this case, changing the default to nil, is the same as just removing the variable. I'm open to it though, in the few years since evil-collection has been up, this topic seems to recur once a year, and it may just be easier to remove the flag and call it a day.

**Comment by yyoncho** [comment]
> Can you link some of them so I can get a better picture?

The point is that the lsp-mode and lsp protocol in general, have a candidate text that is not the thing that is going to be inserted in the buffer. Thus the users see something like `method(String param1, String param2)` in buffer and it looks like it is already inserted which is confusing.

> If company-tng is not a good fit for those backends, I think improving that flow, as @dgutov mentioned, is a good idea

Even if we do, it all will be at the cost of degrading the usability of lsp-mode(e. g, disabling snippets and disabling the multiline completions like YCM do) and it still won't be a good candidate for being the default option from lsp-mode perspective and most likely from the perspective of the average user.

> The philosophy here has always been more along the lines of 'enable everything, let the user disable what they don't want' whereas it seems most emacs packages are the reverse 'enable nothing, let the user enable what they want'. If we were to do the latter, I don't think this package would have been as useful.

At lsp-mode we do pretty much the same.

**Comment by jojojames** [comment]
> The point is that the lsp-mode and lsp protocol in general, have a candidate text that is not the thing that is going to be inserted in the buffer. Thus the users see something like method(String param1, String param2) in buffer and it looks like it is already inserted which is confusing.

It would still be helpful to see the bug reports, so we can see what the nature of them are and maybe we can improve that area. Your current comment is an example of that happening.

e.g. 

> Thus the users see something like method(String param1, String param2) in buffer and it looks like it is already inserted which is confusing.

e.g. https://github.com/company-mode/company-mode/blob/4286972775832e29434becc6c72e767319139a1c/company-tng.el#L166 looks to be eglot specific code to maybe block that behavior, or maybe block expansion (not sure). I myself don't see snippet expansion before selection/completion (caveat below).

If this is the only problem of tng+lsp-mode, it might be worth improving that area -first-, right?

> Even if we do, it all will be at the cost of degrading the usability of lsp-mode(e. g, disabling snippets and disabling the multiline completions like YCM do)

I don't agree those are the only things we can do so the conclusion doesn't follow for me. (I'm not sure what you mean by multiline completions, since most snippets are multiline snippets.)

> At lsp-mode we do pretty much the same.

++

Caveat mentioned:

I wrote a couple functions myself to improve yasnippet+company mode+tng, to get the exact behavior I want.

1. Tab cycles candidates if there's a list of candidates.
2. Tab completes a candidate if there is one candidate.
3. RET inserts a RETURN unless on a snippet (complete the snippet) or in a snippet expansion.

Now you might say, that's a lot to make tng+company+evil+etcetc packages work, but in my experience, I don't think any default of company makes yasnippet play nice with every other package, though maybe that has changed in the past few years.

As a followup, I will find some time to reset everything back to the defaults of each package and try out interactions between them and evaluate the current state of things.

**Comment by dgutov** [comment]
> I wrote a couple functions myself to improve yasnippet+company mode+tng, to get the exact behavior I want.

FWIW, `company-tng-mode` does 1 (without wraparound), 2 (effectively; it really inserts the candidate when you continue typing, but that ends up the same), and also 3 (the first part of it; it doesn't special-case snippet completions, if that's what you meant).

**Comment by jojojames** [comment]
> FWIW, company-tng-mode does 1 (without wraparound), 2 (effectively; it really inserts the candidate when you continue typing, but that ends up the same), and also 3 (the first part of it; it doesn't special-case snippet completions, if that's what you meant).

Yeah, some of the behavior should be strictly from company-tng. I just tried removing my binds for #2 and it works as you said, so that's nice. (I'm not sure why I used something else before so maybe this is due to some recent changes in company-tng.)

>  and also 3 (the first part of it; it doesn't special-case snippet completions, if that's what you meant).

Yeah, I meant mainly the special case completion for snippets was the extra I added.

e.g.

```
    (defun j-company-expand-yasnippet-or-return ()
      "Expand yas template or call RET normally.

If `yasnippet' expansion in progress, always complete selection."
      (interactive)
      (cond
       ;; `yasnippet' expansion in progress.
       ((yas-current-field)
        (call-interactively #'company-complete-selection))
       ;; Check the type of the candidate.
       ((and company-active-map
             company-selection-changed
             (car company-candidates) ;; Making sure there are candidates.
             (let ((candidate (nth company-selection
                                   company-candidates)))
               (or
                ;; This might work for `eglot'.
                ;; (get-text-property 0 :label candidate)
                ;; `company-lsp'
                (get-text-property 0 'lsp-completion-item candidate)
                ;; `company-sourcekit'
                (get-text-property 0 'sourcetext candidate)
                ;; `yasnippet'
                (get-text-property 0 'yas-template candidate))))
        (call-interactively #'company-complete-selection))
       (:default
        (when company-selection-changed
          (company-complete-selection))
        (let ((company-active-map))
          (call-interactively (key-binding (kbd "RET")))))))

      (define-key company-active-map [return] 'j-company-expand-yasnippet-or-return)

```

The last bit of sugar over company/tng is to try to make backspace work a little more intelligently.

```
    (defvar company-cancel-or-backspace
      `(menu-item "" nil :filter ,(lambda (&optional _)
                                    (when company-selection
                                      #'company-abort)))
      "If we made a selection during company completion, cancel it.")

    (define-key company-active-keymap (kbd "DEL") company-cancel-or-backspace)
```

With these changes, although there are still hiccups here and there, eglot+evil+company/tng+yasnipppet all work reasonably well for me.

**Comment by dgutov** [comment]
> I just tried removing my binds for #2 and it works as you said, so that's nice. (I'm not sure why I used something else before so maybe this is due to some recent changes in company-tng.)

It was probably from before `company-tng` was added.

> The last bit of sugar over company/tng is to try to make backspace work a little more intelligently.

It might make sense to move it to tng as well. Does YCM remove selection on backspace too?

> Yeah, I meant mainly the special case completion for snippets was the extra I added.

No sure about this one: snippets are undoubtedly a problem for that UI, but having RET do double duty seems like a step back.

> With these changes, although there are still hiccups here and there, eglot+evil+company/tng+yasnipppet all work reasonably well for me.

It should depend on the language server used. IIUC, some of them add function arguments to the completions, and some don't.

It would of course be preferable, from my side, if both Eglot and LSP Mode moved that text strictly to annotations, but I don't know how hard that is to implement.

**Comment by yyoncho** [comment]
> It would still be helpful to see the bug reports, so we can see what the nature of them are, and maybe we can improve that area. Your current comment is an example of that happening.

https://gitter.im/emacs-lsp/lsp-mode?at=5ebee15713878c30b58009bb Here is a sample report, you can search in gitter or in discord for complaints. 

> If this is the only problem of tng+lsp-mode, it might be worth improving that area -first-, right?
> ...
> RET inserts a RETURN unless on a snippet (complete the snippet) or in a snippet expansion.

This can be an improvement(or at least less confusion for the user). I will suggest even having it unconditionally.

**Comment by dgutov** [comment]
> This can be an improvement(or at least less confusion for the user). I will suggest even having it unconditionally.

In tng-mode? If (kind = snippet), RET completes, otherwise inserts RETURN?

**Comment by yyoncho** [comment]
> In tng-mode? If (kind = snippet), RET completes, otherwise inserts RETURN?

company-mode should ask the backend using a different method - because even if kind = method the thing to insert can be still a snippet. But IMHO better to have RET unconditionally insert the item no matter if it is a snippet or not(I am not tng user so I might be wrong).

**Comment by dgutov** [comment]
> company-mode should ask the backend using a different method - because even if kind = method the thing to insert can be still a snippet

You probably mean that it would complete the method AND insert a snippet because they are enabled. Right?

> But IMHO better to have RET unconditionally insert the item no matter if it is a snippet or not(I am not tng user so I might be wrong)

It might make sense: after all, the user has already typed TAB at least once to indicate that they wanted to interact with completion.

Any Vim users in this thread? Does YCM do something similar?

@nikital, WDYT?

**Comment by yyoncho** [comment]
> You probably mean that it would complete the method AND insert a snippet because they are enabled. Right?

I mean that the CompletionItem has 2 properties, one is `kind`(the thing to use for the items) and also it has `insertTextFormat` which can be `plainText` or `snippet`. Thus any `kind` can be actually `snippet`

**Comment by yyoncho** [comment]
cc @kiennq

**Comment by jojojames** [comment]
> It might make sense to move it to tng as well. Does YCM remove selection on backspace too?

I don't think so.

> No sure about this one: snippets are undoubtedly a problem for that UI, but having RET do double duty seems like a step back.

Maybe, it was just one approach I took to making snippets + tng work for me.

> https://gitter.im/emacs-lsp/lsp-mode?at=5ebee15713878c30b58009bb Here is a sample report, you can search in gitter or in discord for complaints.

Thanks.

> It might make sense: after all, the user has already typed TAB at least once to indicate that they wanted to interact with completion.

As an addition, I think it'd be pretty cool to be able to preview these snippet/completions (through an overlay potentially?) tng/ycmd's way of inserting the text directly after a tab makes tabbing through completions awkward, but some sort of visual preview would be nice.

> Any Vim users in this thread? Does YCM do something similar?

I don't know if YCMD has snippets support, recently tried it again but didn't go far enough to see how it works. I'm guessing there are other snippet packages (ultisnips when I still used vim) that also doesn't play nice with ycmd.

**Comment by kiennq** [comment]
A little weight in as both `lsp-mode` and `company-tng` user from my side.

I'm using `company-tng-mode` with `company-tng-auto-configure` turn off so I don't have snippets disabled by `company-tng-mode`. I do experience something like the inserted phrase differs from what's selected in `company-mode` popup, but that's mostly a little annoying at first and becomes much more familiar later on.

I think LSP's snippet and Emacs concept of snippet is different. In Emacs, anything that expanded to different from display is considered snippet, whereas in LSP, typing `scripts:test` can be expanded to `$scripts:test` but it's not considered a snippet, just a normal candidate item replacement. So to put something like press `RET` to expand snippet but just insert Enter when it's not is something definitely not really working out so well in LSP world.
Moreover, another thing to consider is that the LSP candidate item can have a prefix different from what's reported to `company-mode` via capf interface: the prefix reported to capf is before the completion happens, the prefix of candidate item returned by server can differ from that. The current `company-tng` that shows prereview of the selected item is not really fit for that, we can either:
- Disable the preview front-end
- Add capability to `company-tng` to show the expanded item instead. This will likely require new data to be passed to `company-tng`, for example the replacement range and replacement text.


Back to the original question, perhaps just set `company-tng-auto-configure` to `nil` is a better fit here.

**Comment by yyoncho** [comment]
> * Add capability to `company-tng` to show the expanded item instead. This will likely require new data to be passed to `company-tng`, for example the replacement range and replacement text.

IMHO this is interesting area to explore. One way to achieve it is to have a backend method - `insert preview`.

**Comment by dgutov** [comment]
@jojojames 

> I don't think so.

Perhaps some other popular package for Vim does.

Or we could add it anyway, if no tng users see a downside.

> I don't know if YCMD has snippets support, recently tried it again but didn't go far enough to see how it works. I'm guessing there are other snippet packages (ultisnips when I still used vim) that also doesn't play nice with ycmd.

I meant whether YCMD has some counterpart to the proposal "if user has pressed TAB at least once RET will insert completion".

**Comment by dgutov** [comment]
@kiennq 

> Disable the preview front-end

That's an option, of course. But then what is left, if you also disable `company-tng-auto-configure`? The change to the value of `company-selection-default`?

**Comment by dgutov** [comment]
@yyoncho 

> IMHO this is interesting area to explore. One way to achieve it is to have a backend method - insert preview.

If feasible, it should rather be something like `preview` which returns replacement range and text, which can be used to create the preview overlay (like @kiennq suggested).

I wonder also if that command could somehow be merged/reused with the `insert` action you proposed in here: https://github.com/emacs-lsp/lsp-mode/pull/2711#issuecomment-798964844

That look difficult, though, given that the latter can end up in a different state (inside snippet insertion UI, for example), and with a corresponding different value of point.

**Comment by kiennq** [comment]
> But then what is left, if you also disable `company-tng-auto-configure`? The change to the value of `company-selection-default`?

Not only that, we still have:
- Ability to have non-selection state like VIM
- Ability to insert an item from popup without explicitly pressing RET, you can just tab to that item and press other key to continue. That would save a lot of keypresses.

I think that two is the core functionalites of `company-tng`, the overlay visual is nice, but isn't really optimized/working in all cases now.

**Comment by yyoncho** [comment]
@dgutov 

> If feasible, it should rather be something like preview which returns replacement range and text, which can be used to create the preview overlay (like @kiennq suggested).

> I wonder also if that command could somehow be merged/reused with the insert action you proposed in here: emacs-lsp/lsp-mode#2711 (comment)

Seems like it will be better to pass the text ranges to company as @kiennq . It will allow fixing other  issues as well, like - insert the common prefix which is now broken. 

> That look difficult, though, given that the latter can end up in a different state (inside snippet insertion UI, for example), and with a corresponding different value of point.

Agree. But definetelly something interesting to explore.

**Comment by dgutov** [comment]
@kiennq

> Ability to have non-selection state like VIM

It's implemented outside of `company-tng` package now ;-)

> Ability to insert an item from popup without explicitly pressing RET, you can just tab to that item and press other key to continue. That would save a lot of keypresses.

And that requires either `company-tng-frontend` or non-nil `company-auto-commit`.

**Comment by dgutov** [comment]
@yyoncho

> It will allow fixing other issues as well, like - insert the common prefix which is now broken.

It might. Though implementing it when prefixes can begin at different positions in the same completions list sounds a little tricky.

> But definetelly something interesting to explore.

I'm happy to review a PR with that effect, experimental or not.

Back when we discussed extracting snippet expansion into a separate action (which IIUC we now have determined is incompatible with LSP), I figured backends could return the snippet source, and Company would be able to pre-render it in a similar way. Or insert, when needed. Now we're going to delegate snippet expansion responsibility to the backends, I guess, and that will require two different backend actions. And every backend reimplementing this stuff. :disappointed:

**Comment by nikital** [comment]
Hi all,

As context for my next suggestion, I'd like to note that two strong assumption of `company-tng` were

- Tooltip text is the same as the inserted text, so it makes sense to preview using tooltip text
- Confirming a company selection has no further side effects, so it makes sense to confirm implicitly

So once we start having side effects upon completion that change the inserted text, the user experience gets weird since the side effects come at an unexpected time and implicitly.

IIUC @dgutov and @kiennq propose to fix it by trying to incorporate the side effect into the preview, so that when the selection is confirmed the text on screen doesn't change. This is complicated to implement because it requires modifying all backends to generate a preview[1], but should result in high quality completions.

I would like to bring up another option to improve the user experience across all backends. The idea is to commit to the assumption that "tooltip text is the same as the inserted text", which means that:

- TNG will still preview based on the tooltip
- When a selection is confirmed "implicitly" (i.e. by hitting an unrelated key), instead of calling `company-complete-selection` we would cancel the company completion and insert the tooltip text from the preview.
- If a user wishes to actually confirm the selection with possible side effects, bind a key to explicitly call `company-complete-selection`, such as `RET` or `C-j`.

This way the user who's only interested in plain keyword completion can just type away and hit `TAB` from time to time to complete, but when interested in snippets or other types of side-effects (automatic imports, arguments, prefix, etc.) they can use the explicit completion key.

I like this model because it means that nothing unexpected happens unless I request it with `C-j` and I personally would be satisfied with it. So I wondered what you folks think and what would be the downsides.

[1] Is it even possible for LSP? I thought that sometimes LSP sends additional "editing commands" only when the completion is ended.

**Comment by dgutov** [comment]
> This is complicated to implement because it requires modifying all backends to generate a preview

Not exactly: only those that have "surprising" side-effects. For the rest, we can create the default preview implementation. If a backend is otherwise straightforward but has snippet expansion in `post-completion`, we could opt to simply continue settings its "enable snippet" variable to nil until the backend implements the `preview` action.

> When a selection is confirmed "implicitly" (i.e. by hitting an unrelated key), instead of calling company-complete-selection we would cancel the company completion and insert the tooltip text from the preview.

I figured if we add the notion of "preview", we might as well add support for snippets with it. Meaning, it would show the snippets in their expanded state (maybe truncated, if they span several lines).

What you're suggesting is a certainly valid approach, but the user gets less features, and I'm not sure if it's easy to do with LSP ("truncate" the completions to just the method name, for example). The trouble with it, the server controls too much, and you can't change on-the-fly whether the current completion requret is going to want to use snippets or not (that only gets declared when the server starts).

> If a user wishes to actually confirm the selection with possible side effects, bind a key to explicitly call company-complete-selection, such as RET or C-j.

Would `company-tng-mode` have such a binding by default? E.g. on RET?

I'd also like to bring your attention back to two other suggestions that have been presented here:

* Have a special command on `<backspace>` which also resets `company-selection` to nil.
* Have a `RET` binding such that it checks whether `company-selection` is non-nil. If so, it triggers `company-complete-selection`, snippet expansion, and so on. If not, it behaves as a regular `RET`.

Both kind of make sense to me, but might also create a departure from the workflow that `company-tng` has tried to imitate.

**Comment by dgutov** [comment]
@yyoncho @kiennq BTW, to try out the "new backend action which affects how completions look in the popup", you can utilize the existing but undocumented `pre-render` action which I regularly forget about (originally from https://github.com/company-mode/company-mode/issues/437).

To support the case where pre-render produces a shorter string (such as turning a method with arguments into one without), I think only this additional patch is needed:

```diff
diff --git a/company.el b/company.el
index 2c3d2dc..c0a9d25 100644
--- a/company.el
+++ b/company.el
@@ -3084,7 +3084,7 @@ If SHOW-VERSION is non-nil, show the version in the echo area."
             ;; `lisp-completion-at-point' adds a space.
             (setq annotation (string-trim-left annotation))))
         (push (list value annotation left) items)
-        (setq width (max (+ (length value)
+        (setq width (max (+ (length (company--pre-render value))
                             (if (and annotation company-tooltip-align-annotations)
                                 (1+ (length annotation))
                               (length annotation)))
```

**Comment by nikital** [comment]
@dgutov

> I figured if we add the notion of "preview", we might as well add support for snippets with it.

I agree that if it's feasible to generate consistent preview in all relevant backends, then this is the way to go.

For some reason I thought you can't generate a preview of the inserted text from LSP without actually confirming and finishing the completion, but now that I look at the spec, it looks like it's possible, which is great :) In that case all I wrote below might be irrelevant.

> I'm not sure if it's easy to do with LSP ("truncate" the completions to just the method name, for example). The trouble with it, the server controls too much, and you can't change on-the-fly whether the current completion request is going to want to use snippets or not (that only gets declared when the server starts).

That's why I suggested that upon an "implicit" completion, we would **cancel** the completion on the backend and directly insert the label from the tooltip. This should inhibit all side-effects since from the server's point of view nothing was actually completed. I know that this might seem like a broken design decision but I still wanted to cautiously propose it.

> Would `company-tng-mode` have such a binding by default? E.g. on `RET`?

Yes, I was thinking about `C-j` or something that doesn't interfere with editing. `RET` is problematic for my proposal, when you want to complete a word and immediately insert a newline (and not have to hit `RET` twice, first to confirm, second to insert newline).

> I'd also like to bring your attention back to two other suggestions that have been presented here:
> - Have a special command on <backspace> which also resets company-selection to nil.

Unfortunately I didn't understand this suggestion. For reference, currently backspace in TNG looks like this:

1. Type "He", buffer looks like `He|`, Company tooltip opens
2. Hit `Tab`, first completion is inserted: `Hello|` tooltip remains open
3. Hit `BS`, completion is implicitly confirmed, tooltip closes, `BS` is inserted, resulting: `Hell|`

what of the above would be different under the proposed `BS` behavior?

> - Have a `RET` binding such that it checks whether `company-selection` is non-nil. If so, it triggers `company-complete-selection`, snippet expansion, and so on. If not, it behaves as a regular `RET`.

I think I'm missing some nuance here, isn't this what currently happens in TNG and that's that causing our problem? It's just not specific to `RET`, but happens with any key that is outside of `company-active-map`. I'll write the user scenarios explicitly so that you could point out if I missed something:

Scenario 1 (no selection):
1. Type "He", buffer looks like `He|`, Company tooltip opens
2. We don't want a completion, type `RET`, Company tooltip closes, newline inserted, buffer looks like

        He
        |

Scenario 2 (with selection):
1. Type "He", buffer looks like `He|`, Company tooltip opens
2. Hit `Tab`, first completion is selected, buffer looks like `Hello|`, tooltip remains open
3. Type `RET`, completion is implicitly confirmed, tooltip closes, newline inserted, buffer looks like

        Hello
        |

Under scenario 1 there will be no snippet expansion, under scenario 2 there might be snippet expansion if "Hello" is a snippet. In that case it will expand after `RET`, which might be undesired. What would be different with the proposed `RET` binding?

**Comment by dgutov** [comment]
> That's why I suggested that upon an "implicit" completion, we would cancel the completion on the backend and directly insert the label from the tooltip

How to create appropriate labels in the tooltip is still an open problem. E.g, one of the present examples is jdtls returning completions with parens and arguments in them, and lsp-mode putting those in the tooltip.

> RET is problematic for my proposal, when you want to complete a word and immediately insert a newline (and not have to hit RET twice, first to confirm, second to insert newline).

I think that's less problematic, ergonomically, than when you weren't going to insert the newline (and thus may have avoided pressing RET at all). If you finger is on RET already, pressing it twice shouldn't be too annoying.

> Unfortunately I didn't understand this suggestion. For reference, currently backspace in TNG looks like this:
> ...
> what of the above would be different under the proposed BS behavior?

It will be:

3. Hit BS, completion selection is undone, completion is un-inserted, tooltip stays open, BS binding is called, result: `H|`.

It never occurred to me that someone would want BS to act on the "inserted" completion, though.

> Under scenario 1 there will be no snippet expansion, under scenario 2 there might be snippet expansion if "Hello" is a snippet. In that case it will expand after RET, which might be undesired. What would be different with the proposed RET binding?

Also just the last step of the second scenario:

3. Type RET, completion is *explicitly* confirmed, tooltip closes, newline is *not* inserted, buffer looks like

```el
Hello|
```

Hmm. Perhaps both proposals would look better if there selected candidate weren't "inserted" right away? Meaning, no "preview" frontend. Not sure.

Maybe we could do that for snippet completions only. If we created a reliable way to detect those.

**Comment by jojojames** [comment]
Re: backspace functionality. It's:

Type "He", buffer looks like He|, Company tooltip opens

Type "He", buffer looks like He|, Company tooltip opens
Hit Tab, first completion is inserted: Hello| tooltip remains open
Hit BS, completion is aborted, buffer looks like He|

I think it's useful for when I'm tabbing through a list of selections, and want none of them, backspacing through a 20 letter completion then is annoying, so I like backspace to DWIM in this case.

> Yes, I was thinking about C-j or something that doesn't interfere with editing. RET is problematic for my proposal, when you want to complete a word and immediately insert a newline (and not have to hit RET twice, first to confirm, second to insert newline).

I think this is true for non snippets insertions but would work better for snippets. (Especially since snippets also uses tabs to traverse to the next inner section of the snippet.

Recorded a quick video of my company-mode + yasnippet.

https://www.dropbox.com/s/edvbx9osgl8qla4/Screen%20Recording%202021-04-28%20at%2012.41.23%20AM.mov?dl=0

I have RET behave 'normally' (as in enters in a RET) unless it's expanding a snippet or completing within a snippet. This allows me to use tab to move through snippets as well as well as for selecting the completion.

**Comment by dgutov** [comment]
@jojojames Looking at it again, I think it *does* make sense. Seems like a nice time-saving measure, instead of having to press backtab a bunch of times. And how often does one want to backspace over the just-inserted completion anyway?

But it would probably feel better if the tng preview overlay used some non-default background, to denote that the string is not "completely" inserted in the buffer yet. Then having backspace delete the whole not-yet-inserted part would be easy to anticipate.

Not sure about the "smart" RET behavior yet.

**Comment by dgutov** [comment]
@nikital What do you think about the backspace thing? Of course, we could make that behavior optional.

**Comment by nikital** [comment]
@dgutov 

Re backspace thing: I'm personally against having it be the default, since TNG would no longer behave like Vim (the completion would no longer be inserted upon `TAB`, which is kind of the core of TNG for me).

Current TNG behavior allows Vim/YCM users to carry over their muscle memory into Company. I think that's why TNG is on by default in evil-collection :)
The backspace thing might be a feature that some people might like, but I believe that out-of-the-box muscle memory compatibility with Vim is more important.

Re this issue in general: I plan to create a Vim/YCM setup with snippets and templates and LSP, study their behavior and report here how it works. Hopefully seeing how YMC integrated snippets/templates will give us some ideas. This has been on my TODO since May but I didn't do it yet :(

**Comment by dgutov** [comment]
> I'm personally against having it be the default, since TNG would no longer behave like Vim

Fair enough. Let's put a pin in it for now. Though if someone wanted to submit a PR adding this as an optional feature, welcome!

> I plan to create a Vim/YCM setup with snippets and templates and LSP, study their behavior and report here how it works

Looking forward to it. :+1:

(No pressure)
