### ISSUE TITLE
Conflict with mu4e 1.3.9

### ISSUE THREAD

**Issue by A6GibKm** [emacs-evil/evil-collection#314]
Whenever I run `mu4e` I get the following error

```
error in process filter: evil-collection-mu4e-replace-region: Search failed: "
  Basics"
error in process filter: Search failed: "
  Basics"
```

And see an empty buffer. To get to the dashboard I have to refresh.

This is happening with mu 1.3.9.

**Comment by tpeacock19** [comment]
I am experiencing the same issue. There was a commit in mu4e changing how the main buffer is created https://github.com/djcb/mu/commit/b1369b6ad9f9c1a7e8d363dc8c72b503ffd11753

I've put the following into my config and it seems to take care of it.  

```elisp
  (remove-hook 'mu4e-main-mode-hook 'evil-collection-mu4e-update-main-view)
  (advice-add 'mu4e~main-redraw-buffer :after 'evil-collection-mu4e-update-main-view)
```

although a hook would be preferred, iIthink since it's just replacing text it shouldn't cause any problems using an advice.

**Comment by tpeacock19** [comment]
I'm experiencing the same thing. There was a commit in mu4e that's changed how the main buffer is built: https://github.com/djcb/mu/commit/b1369b6ad9f9c1a7e8d363dc8c72b503ffd11753

I've added the below to my config and its fixed the issue. Although a hook would be better, since its just changing text, I dont think the advice should be an issue.

```elisp
  (remove-hook 'mu4e-main-mode-hook 'evil-collection-mu4e-update-main-view)
  (advice-add 'mu4e~main-redraw-buffer :after 'evil-collection-mu4e-update-main-view)

```

**Comment by Ambrevar** [comment]
I can't test this since I'm no longer using mu4e.
Would you like to send a pull request to fix this?

**Comment by tpeacock19** [comment]
Sure, I've just submitted one. Its my first so please let me know if I did it correctly. Thanks!

**Comment by tpeacock19** [comment]
on further investigation it seem like we will need to use a hook. the function locks the buffer so i've submitted an issue with mu4e to see if we can get it created.

**Comment by Ambrevar** [comment]
OK, thanks for this investigation!

**Comment by Ambrevar** [comment]
Can we close this?

**Comment by Emantor** [comment]
Yes, I have tested latest `mu` with evil-collection and with the fix in `mu` (and the advice removed) it works correctly again.

**Comment by Ambrevar** [comment]
Thanks!
