### ISSUE TITLE
Add elpher keybindings

### ISSUE THREAD

**Issue by jgarte** [emacs-evil/evil-collection#463]
I'm just opening this as a public bookmark for myself or anyone else. I hope to get to this soon.

https://thelambdalab.xyz/elpher/

**Comment by tgvaughan** [comment]
Hi @jgarte, I'm the author of elpher.  Hopefully it shouldn't be necessary to include in evil-collection, since I try to add sensible (for some definition of sensible) bindings for both evil and non-evil users.  If you feel something's amiss, let use know over on the mailing list: https://lists.sr.ht/~michel-slm/elpher.
