### ISSUE TITLE
Missing unimpaired mapping `[p`

### ISSUE THREAD

**Issue by BlueDrink9** [emacs-evil/evil-collection#477]
I'm greatly missing the keybinding `[p` for a linewise paste on the previous line, without having to move the cursor there or create a new line.

From unimpaired.txt:

> These are experimental:

    *>p*    Paste after linewise, increasing indent.
    *>P*    Paste before linewise, increasing indent.
    *<p*    Paste after linewise, decreasing indent.
    *<P*    Paste before linewise, decreasing indent.
    *=p*    Paste after linewise, reindenting.
    *=P*    Paste before linewise, reindenting.

    |]p|, |[p|, |[P|, and |]P| have also been remapped to force linewise pasting,
    while preserving their usual indent matching behavior.

**Comment by condy0919** [comment]
Thanks for pointing out the missing part of unimparied. :-)

**Comment by jojojames** [comment]
PR would be nice, otherwise this would be nice if I find some time.

**Comment by condy0919** [comment]
https://github.com/emacs-evil/evil-collection/commit/9be3805b60d03fc6e0d45cb3decb5c6703395cf4 adds basic support of `[p` and `]p`.

**Comment by jojojames** [comment]
From looking at the doom issue, looks like there may be subtle implementation differences between what's in evil-collection and doom. Instead of doing that, I'd encourage people to contribute back to the community. PRs are always welcome.

Anyways, we should be able to close this issue now that theres something in evil-collection for this.
