### ISSUE TITLE
Lispy redundancy

### ISSUE THREAD

**Issue by MaxCan-Code** [emacs-evil/evil-collection#511]
https://github.com/emacs-evil/evil-collection/blob/8d10ad4ea59752595de37a8ddc44e8d3fb14fe89/modes/lispy/evil-collection-lispy.el#L530-L533
this is redundant with lispy defaults, can we remove such instances?

**Comment by jojojames** [comment]
We prefer to rebind everything for consistency and that's a new keymap being declared there.

**Comment by MaxCan-Code** [comment]
lispy bindings are vi like by default, so that is sufficient consistency. Explicitly rebinding everything is confusing for new users to check what evil-collection actually rebound

**Comment by jojojames** [comment]
There's a couple ways to go about it withs pros and cons each. We chose one way and take the cons of that approach. As a user, you can 1. adapt 2. disable lispy 3. work around it, etc etc.

As for your comments, I don't necessarily agree. I think it'd be more confusing for a user to have to check lispy's bindings + evil-collection's bindings separately to see what's bound and not. Also your example seems to be 'make believe' in the sense that for the case where we're rebinding the same key to the same functionality, the user can't tell either way.

Now if you're saying the user has to check evil-collection to see what bindings are there, well that's true of all modes.

> lispy bindings are vi like by default, so that is sufficient consistency.

I don't agree, if if was sufficient consistency, we wouldn't have a need for evil-collection in the first place.

What problem would you be trying to solve for users?

**Comment by MaxCan-Code** [comment]
This problem for example: https://libredd.it/r/emacs/comments/ldrsmz/lispyvillelispy_guide_for_beginner/go4iv38/?context=3

I doubt any new users would only refer to evil-collection-lispy when they learn lispy, they would first read the lispy docs. Then they check evil-collection-lispy after to see the diff. So they'll be checking both bindings separately anyways. It should be easier for users to know the bindings by the diff. In the case of redundant maps users have to double check that it's actually not rebound, which adds confusion

Commenting the overridden bindings helps, but this comment is wrong
https://github.com/emacs-evil/evil-collection/blob/8d10ad4ea59752595de37a8ddc44e8d3fb14fe89/modes/lispy/evil-collection-lispy.el#L463
it should be `-> n` and not `-> w`

**Comment by jojojames** [comment]
> This problem for example: https://libredd.it/r/emacs/comments/ldrsmz/lispyvillelispy_guide_for_beginner/go4iv38/?context=3

Can you succinctly how this relates to the problem you're trying to solve and how your proposal solves it?

> I doubt any new users would only refer to evil-collection-lispy when they learn lispy, they would first read the lispy docs.

There could be a use case where a user is already familiar with lispy and would only want to see what the evil-collection version is. There is also the use case where a user is unfamiliar with both lispy and evil-collection but is ok with just looking at evil-collection.

> It should be easier for users to know the bindings by the diff.

What diff? If a user is both new to lispy and evil-collection, they'd have to look at every single binding if they actually want to figure out bindings through 'diffing'. I propose another alternative, just look at evil-collection's version where we bound everything.

> In the case of redundant maps users have to double check that it's actually not rebound, which adds confusion

If a user is interested in keybinding A in lispy.el and they are using evil-collection, and they are interested in whether or not keybinding A is bound or not, they will have to look at evil-collection whether or not keybinding A is actually bound. This isn't a 'redundant maps' issue as much as a 'multiple keybinding sets' issue. 

Reading through: https://libredd.it/r/emacs/comments/ldrsmz/lispyvillelispy_guide_for_beginner/go4iv38/?context=3 that you linked, it also seems to be related more to 'multiple keybinding sets' than redundant maps. A solution for that doesn't involve redundant binds.

> it should be -> n and not -> w

Please PR and I can take a look if that's true.

**Comment by MaxCan-Code** [comment]
> > This problem for example: https://libredd.it/r/emacs/comments/ldrsmz/lispyvillelispy_guide_for_beginner/go4iv38/?context=3
>
> Can you succinctly how this relates to the problem you're trying to solve and how your proposal solves it?

From my point of view, "the stuff evil-collection adds only increases the confusion" from daviwil is referring to the redundant bindings

> There could be a use case where a user is already familiar with lispy and would only want to see what the evil-collection version is.

They could also be interested in seeing how the evil-collection version is _different_, redundant binding won't help in that case

> There is also the use case where a user is unfamiliar with both lispy and evil-collection but is ok with just looking at evil-collection.

How would evil-collection alone, with no documentation, tell them how to use lispy?
 
> > It should be easier for users to know the bindings by the diff.
> 
> What diff? If a user is both new to lispy and evil-collection, they'd have to look at every single binding if they actually want to figure out bindings through 'diffing'. I propose another alternative, just look at evil-collection's version where we bound everything.

They would first see every single binding in the lispy docs. Figuring out redundant binds increases context switching, which is opposite to the goal in the README

> > In the case of redundant maps users have to double check that it's actually not rebound, which adds confusion
> 
> If a user is interested in keybinding A in lispy.el and they are using evil-collection, and they are interested in whether or not keybinding A is bound or not, they will have to look at evil-collection whether or not keybinding A is actually bound.

They can look at evil-collection to see whether or not binding A is _rebound_

> Reading through: https://libredd.it/r/emacs/comments/ldrsmz/lispyvillelispy_guide_for_beginner/go4iv38/?context=3 that you linked, it also seems to be related more to 'multiple keybinding sets' than redundant maps. A solution for that doesn't involve redundant binds.

It would help if one of the multiple keybinding sets is non-redundant

> > it should be -> n and not -> w
> 
> Please PR and I can take a look if that's true.

Will do

**Comment by jojojames** [comment]
> From my point of view, "the stuff evil-collection adds only increases the confusion" from daviwil is referring to the redundant bindings

That can't be true because he's referring to bindings that are 'different' AKA different behavior than what he'd expect. So that's the scenario where lispyville -changes- the binding. Redundant bindings -don't- affect a user if they don't bother to look up the bindings in the first place. 

E.g. "But some other times, they are mystery, wasting a lots of time to guess the strange edit effects, and trying to fix the edits that I don't understand."

This wouldn't happen if the bindings were the same.

> They could also be interested in seeing how the evil-collection version is different, redundant binding won't help in that case

My point wasn't that "These are the only ways people use evil-collection", my point is that there are -multiple- ways to use evil-collection and considering all the approaches and its pros and cons is the right thing to do.

> How would evil-collection alone, with no documentation, tell them how to use lispy?

Evil collection doesn't teach them how to use lispy, they can use lispy for that. Evil-collection does however, show them what it binds -for- lispy. Important distinction.

> They would first see every single binding in the lispy docs. Figuring out redundant binds increases context switching, which is opposite to the goal in the README

'Reducing contexting switching' is in the context of: "As soon as “moving around” gets hardwired to <hjkl>, it becomes frustratingly inefficient not to have it everywhere." E.g. the context switch of NOT having evil-like keybindings, not this "context switching from having to look at two sets of documentation".

> They can look at evil-collection to see whether or not binding A is rebound

That doesn't change what I said. If they are interested in whether A bound/rebound/unbound, they're going to have to look at evil-collection regardless. 

> It would help if one of the multiple keybinding sets is non-redundant

I don't think it would help in any meaningful way, especially since that link -does not- seem to be about redundant keymaps. See ^.

**Comment by MaxCan-Code** [comment]
> That can't be true because he's referring to bindings that are 'different' AKA different behavior than what he'd expect. So that's the scenario where lispyville -changes- the binding. Redundant bindings -don't- affect a user if they don't bother to look up the bindings in the first place.

Not having to look up the look up the bindings is the ideal for the user. However when the bindings are inconsistent with the first class reference (lispy docs in this case), the user would have to look it up. Having redundant code hinders the lookup process since that is not what the user is looking for in that (possibly common) case

So far there are 2 cases for users looking up evil-collection-lispy.el:
1. Want to see all lispy bindings they can use
2. Binding inconsistent with lispy docs, want to find non-redundant remaps quickly

Which spawns 2 questions:
- Would users expect most of the evil-collection-lispy bindings to be covered in the lispy docs?
- Which user case is more likely?

> E.g. "But some other times, they are mystery, wasting a lots of time to guess the strange edit effects, and trying to fix the edits that I don't understand."
> 
> This wouldn't happen if the bindings were the same.

True

> My point wasn't that "These are the only ways people use evil-collection", my point is that there are -multiple- ways to use evil-collection and considering all the approaches and its pros and cons is the right thing to do.

True. I'm not sure about all the use cases, but I tried to consider common cases where users look up the bindings above

> Evil collection doesn't teach them how to use lispy, they can use lispy for that. Evil-collection does however, show them what it binds -for- lispy. Important distinction.

True. My concern is whether redundant information should be shown to users when they look up the bindings

> 'Reducing contexting switching' is in the context of: "As soon as “moving around” gets hardwired to , it becomes frustratingly inefficient not to have it everywhere." E.g. the context switch of NOT having evil-like keybindings, not this "context switching from having to look at two sets of documentation".

Good to know

> > They can look at evil-collection to see whether or not binding A is rebound
> 
> That doesn't change what I said. If they are interested in whether A bound/rebound/unbound, they're going to have to look at evil-collection regardless.

True

> > It would help if one of the multiple keybinding sets is non-redundant
> 
> I don't think it would help in any meaningful way, especially since that link -does not- seem to be about redundant keymaps. See ^.

Did you consider all the use cases before concluding that it wouldn't help in any meaningful way?

**Comment by jojojames** [comment]
> Not having to look up the look up the bindings is the ideal for the user. 

This is impossible so we'll just have to assume the user will have to look up bindings at some point.

> However when the bindings are inconsistent with the first class reference (lispy docs in this case), the user would have to look it up.

evil-collection by definition will be inconsistent with the 'first class reference'. The reality is the user will -always- have to look up the bindings.

> Having redundant code hinders the lookup process since that is not what the user is looking for in that (possibly common) case

Not necessarily. It depends on how they look up the bindings. [insert various approaches users may take here] Just using me as one example, 'redundant' bindings never hinder me. In fact, it gives me confidence the new 'binding list' I'm looking at is exhaustive.

Want to see all lispy bindings they can use
Binding inconsistent with lispy docs, want to find non-redundant remaps quickly
Which spawns 2 questions:

> Would users expect most of the evil-collection-lispy bindings to be covered in the lispy docs?

No.

> Which user case is more likely?

It wouldn't surprise me either way. So lets 'pick one and go with it'. 

> True. My concern is whether redundant information should be shown to users when they look up the bindings

My conclusion is your concern is likely disproportionate compared to the average user looking at these bindings. Most user will probably 1. be happy that there's even any bindings at all 2. take a quick skim through of the bindings, taking note of changes/lack of changes to the bindings and 3. will revisit docs (wherever) as they come to want to freshen up their memory/learn new binds, etc.

The 'redundant information', if it -is- a bother, will probably be a factor of 1/100 on an 'annoyance scale'.

> Did you consider all the use cases before concluding that it wouldn't help in any meaningful way?

It'd be helpful to remember the context on why I responded that way. I do not think it will be helpful in any meaningful way to that link you posted (re: eliminating redundant bindings) -especially- since that link was -not- about redundant bindings.
