### ISSUE TITLE
Key Translation not working in Doom Emacs.

### ISSUE THREAD

**Issue by NemoCZmoravia** [emacs-evil/evil-collection#583]
First I want to say that I am new to Emacs and sorry if I'm just being ignorant here in some way.

I use ColemakDh and want to get the "hjkl" navigation back on the home row (preferably to neio).

I tried two of the snippets from the readme.md:

This one only works partially - n and e pairs work, but i refuses to be remapped.
```
(evil-collection-translate-key nil 'evil-motion-state-map
  ;; colemak hnei is qwerty hjkl
  "n" "j"
  "e" "k"
  "i" "l"
  ;; add back nei
  "j" "e"
  "k" "n"
  "l" "i")
```
  
  
  And this one doesn't work at all:
```
(defun my-hjkl-rotation (_mode mode-keymaps &rest _rest)
  (evil-collection-translate-key 'normal mode-keymaps
    "n" "j"
    "e" "k"
    "i" "l"
    "j" "e"
    "k" "n"
    "l" "i"))

;; called after evil-collection makes its keybindings
(add-hook 'evil-collection-setup-hook #'my-hjkl-rotation)
```

I'm not sure if this isn't a Doom Emacs problem, but I got no help on the their discord so I'm asking here now.
(Used latest clean install of Doom Emacs and Emacs 27.1 on PopOS)

**Comment by condy0919** [comment]
I tested `evil-collection-translate-key` in <kbd>M-x proced</kbd>, it works well.

`evil-collection-proced-setup` binds:

- `m` to proced-mark
- `M` to proced-mark-all
- `c`/`C` to proced-mark-children
- the others are irrelevant

``` emacs-lisp
(defun my-mM-rotation (_mode mode-keymaps &rest _rest)
  (evil-collection-translate-key 'normal mode-keymaps
    "c" "m"
    "C" "M"
    "m" "c"
    "M" "C"))
```

Since `my-mM-rotation` makes

- `c` rebind to (lookup-key proced-mode-map `m`) which is `proced-mark`
- `C` rebind to (lookup-key proced-mode-map `M`) which is `proced-mark-all`
- `m`/`M` rebind to (lookup proced-mode-map `c`) which is `proced-mark-children`

After that,

- `c` binds to `proced-mark`
- `C` binds to `proced-mark-all`
- `m`/`M` bind to `proced-mark-children`

It works well.

NOTE: `my-hjkl-rotation` requires the keymap `neijkl` defined.
