### ISSUE TITLE
consider following unimpaired's foot steps for [ and ]

### ISSUE THREAD

**Issue by bling** [emacs-evil/evil-collection#64]
[unimpaired](https://github.com/tpope/vim-unimpaired) is an extremely popular package among vimmers, and one of the most prominent keybindings is using `[` and `]` for navigation.

however, it's just a prefix key.  for example, `[q` and `]q` are used to navigate between the change list.  this affects anything in emacs that derives from `compilation-mode`.

the current guideline binds an action `[` and `]` alone for many modes, making it quite tedious to undo it.

**Comment by Ambrevar** [comment]
The easy fix would be to rebind `[` and `]` to `[[` and `]]` respectively.

Can you provide relevant example for special modes where unimpaired-style bindings would be useful?

**Comment by bling** [comment]
the example i mentioned, `compilation-mode`, affects anything that derives from it; this includes things like `ag` and its derivatives, `flycheck-errors`, and pretty much anything that generates a "list" of things that you can navigate.  pretty much all of these modes will follow the emacs convention of integrating with `previous-error` and `next-error`.  these commands let you visit a file from the list, go back and forth, from _**any**_ buffer, just like in the vim world with unimpaired.

**Comment by Ambrevar** [comment]
OK, so if I get your example, you want to be able to bind something like `[q` and `]q` globally to navigate the error list with `previous-error` and `next-error` from any buffer.  Correct?

If I got you right, then I think you are making a fair point.

@jojojames: Opinion?

**Comment by bling** [comment]
yep!  that's correct.

**Comment by jojojames** [comment]
I'm curious of other's opinions on this too. @noctuid @fbergroth @dieggsy @Somelauw @justbur

Looking at evil-magit, ] and [ are bound to section navigation (I think a few others are like that).

Also curious if you think @noctuid if the key rotation code will help with this. It seems like a more tricky case going from "]" to "]]" unless @bling is fine with just moving "]" out. If it's solvable (makes it easier to remove the "]" for unimpaired), then this is just a question of which defaults are better.

I do like the shortness of "]" in those modes but getting closer to vim/popular vim is a good goal too.

**Comment by bling** [comment]
>  It seems like a more tricky case going from "]" to "]]" unless @bling is fine with just moving "]" out.

yes, i'd be fine with it being `[[` and `]]` by default for all modes, because then it still allows overrides like `[q` and `]q` to take place.

also, there's already `gj` and `C-j` which perform the same thing.

**Comment by noctuid** [comment]
> the current guideline binds an action [ and ] alone for many modes, making it quite tedious to undo it.

I don't use `[` at all currently but would probably only use the current, shorter keybindings. Like I said about `SPC`, I don't think that `evil-collection` should try to avoid binding commonly used global prefix keys. Even if `evil-collection` doesn't bind `[` or `SPC`, there's no guarantee that other packages do the same. This is especially the case for less standard prefix keys. The sane/simple way to give a global keybinding higher priority is with `evil-make-intercept-map`, which is at most two extra lines of configuration. 

> Also curious if you think @noctuid if the key rotation code will help with this. It seems like a more tricky case going from "]" to "]]" unless @bling is fine with just moving "]" out. 

It should work fine assuming `]]` is not bound in the user's intercept map. I can test it out and add it as an example along with `SPC`. I think that the current keybindings should be kept the default instead of assuming that the user wants to use `[` as a prefix key.

**Comment by Somelauw** [comment]
I think that in non-special modes (org, markdown, outline), `[` and `]` should remain unbound, because they would conflict even with commands built-in to Vim/Evil such as `])`, which is bound to `evil-next-close-parens`. This is currently being done in `evil-collection-outline.el`

In special modes, I consider these built-in commands less useful and I agree they can be replaced by more useful ones. Of course, some external plugins such as `evil-unimpaired` can provide key bindings on `[` and `]` that are useful and in this case the user should decide whether `evil-collection` or `evil-unimpaired` gets precedence. The maintainers of `evil-unimpaired` can help by providing a setup function that automatically binds `[` and `]` everywhere after `evil-collection` and other packages have been loaded and as @noctuid has said, the user can provide their own leader keys using `evil-make-intercept-map`.

By the way, I'm not aware of an `evil-unimpaired` package for Emacs other than the one included in Spacemacs. It's not in Melpa.

**Comment by jojojames** [comment]
> By the way, I'm not aware of an evil-unimpaired package for Emacs other than the one included in Spacemacs. It's not in Melpa.

It'd be cool if that could be extracted somehow.

@bling Lets wait until @noctuid PR goes in and see what you think after.

**Comment by noctuid** [comment]
Looking at [evil-unimpaired](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bspacemacs/spacemacs-evil/local/evil-unimpaired/evil-unimpaired.el), the only spacemacs-specific code is `spacemacs/next-error` and `spacemacs/previous-error`.

**Comment by jojojames** [comment]
Closing this now that @noctuid 's PR is in.

If you had other comments @bling, feel free to re-open.
