### ISSUE TITLE
Reqeuest add evil-collection bindings to infererior python mode

### ISSUE THREAD

**Issue by a3madkour** [emacs-evil/evil-collection#721]
For some reason I can't ascertain; and I hope that is because I am missing something, evil just does not work in inferior python mode.  My best guess is that in: https://github.com/emacs-evil/evil-collection/blob/master/modes/python/evil-collection-python.el
it is lacking a hook for inferior-python-mode-hook.

Please let me know if there are ways/workaround that I could do, but I don't see why inferior-python-mode shouldn't be added here. 

Thank you!

**Comment by jojojames** [comment]
You can see in the python file https://github.com/emacs-evil/evil-collection/blob/master/modes/python/evil-collection-python.el it only does 2 things, binds gz & sets the indentation. If that's all you need, please PR the addition to that file. Otherwise what's currently there is likely insufficient.
