### ISSUE TITLE
Odd defaults for Corfu `tab-n-go`?

### ISSUE THREAD

**Issue by Icy-Thought** [emacs-evil/evil-collection#841]
In my personal opinion, `corfu-preselect` should not be hard-coded to `prompt` because there are two other options that also selects the prompt, `valid` & `first`. And changing the option within `:custom` does not work because the function override the value that we have already predefined.

Also, maybe not everyone wants cycle to be set to `t` even though they'd like to use Tab & S-Tab for navigating within Corfu. Hence that option should be *optional*?

Link: https://github.com/emacs-evil/evil-collection/blob/01d791dd63c723c82d5d076570c015e77d3b5680/modes/corfu/evil-collection-corfu.el#L113-L114

**Comment by condy0919** [comment]
Sorry, I don't use corfu. May @aaronjensen explain that?

**Comment by aaronjensen** [comment]
@Icy-Thought these are the defaults because they closest match what vim users are typically used to. If you want something else, you can avoid loading evil collection corfu or override after evil collection corfu loads with setq. Note that you can’t use tab and go with a different preselect, it literally makes sense, so I think you have to change the bindings too. They all go together. The other option is the VS ode style where you select an item and then press enter. You also need to hit escape just to NOT insert an item if you want to press enter to enter an actual newline. 

From a user experience perspective, aside from accounting for familiarity bias, it’s strictly worse.

**Comment by Icy-Thought** [comment]
I was an nvim user and that was not how my completions worked. On enter it would select the valid answer and when other options were available I could just tab and switch to other selection. That's why I was confused when the `tab-n-go` behaved rather strangely. (in comparison)

I guess it's irrelevant since i am the only one complaining. I will make the switch locally and exclude corfu from evil-collections.

**Comment by aaronjensen** [comment]
@Icy-Thought Sounds good. I haven't used vim in a long time and I don't even remember what completion framework I used. I'm glad you'll be able to set it up to work for you, sorry for the confusion/inconvenience.

**Comment by Icy-Thought** [comment]
No worries! :)
https://github.com/hrsh7th/nvim-cmp is what I am using for my current neovim configuration.
